---
apiVersion: v2
name: github-actions-runner-controller
description: Customized actions-runner-controller for GitHub

version: 1.0.0

type: application

maintainers:
  - name: Daniel Muehlbachler-Pietrzykowski
    email: daniel@muehlbachler.io

appVersion: "0.0.0"

dependencies:
  - name: actions-runner-controller
    version: 0.23.3
    repository: https://actions-runner-controller.github.io/actions-runner-controller
