---
global:
  fullnameOverride: simplelogin

controllers:
  main:
    containers:
      main:
        image:
          repository: simplelogin/app-ci
          pullPolicy: IfNotPresent
          tag: v4.40.2

        command:
          - gunicorn
          - "wsgi:app"
          - -b
          - "0.0.0.0:7777"
          - -w
          - "1"
          - --timeout
          - "30"

        envFrom:
          - configMapRef:
              name: simplelogin-config
          - secretRef:
              name: simplelogin-config
          - secretRef:
              name: simplelogin-database

        resources:
          requests:
            cpu: 50m
            memory: 168Mi
          limits:
            cpu: 1
            memory: 320Mi

      handler:
        image:
          repository: simplelogin/app-ci
          pullPolicy: IfNotPresent
          tag: v4.40.2

        command:
          - python
          - email_handler.py

        envFrom:
          - configMapRef:
              name: simplelogin-config
          - secretRef:
              name: simplelogin-config
          - secretRef:
              name: simplelogin-database

        resources:
          requests:
            cpu: 5m
            memory: 168Mi
          limits:
            cpu: 100m
            memory: 232Mi

      runner:
        image:
          repository: simplelogin/app-ci
          pullPolicy: IfNotPresent
          tag: v4.40.2

        command:
          - python
          - job_runner.py

        envFrom:
          - configMapRef:
              name: simplelogin-config
          - secretRef:
              name: simplelogin-config
          - secretRef:
              name: simplelogin-database

        resources:
          requests:
            cpu: 3m
            memory: 136Mi
          limits:
            cpu: 100m
            memory: 200Mi

    initContainers:
      init:
        image:
          repository: simplelogin/app-ci
          pullPolicy: IfNotPresent
          tag: v4.40.2

        command:
          - sh
          - -c
          - "/init.sh"

        envFrom:
          - configMapRef:
              name: simplelogin-config
          - secretRef:
              name: simplelogin-config
          - secretRef:
              name: simplelogin-database

        resources:
          requests:
            cpu: 50m
            memory: 168Mi
          limits:
            cpu: 1
            memory: 320Mi

serviceAccount:
  create: true

defaultPodOptions:
  automountServiceAccountToken: false

service:
  main:
    ports:
      http:
        port: 7777
  handler:
    enabled: true
    controller: main
    type: ClusterIP
    clusterIP: None
    ports:
      email:
        enabled: true
        port: 20381
        protocol: TCP
        targetPort: 20381

ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: cluster-issuer-email-muehlbachler-io
      external-dns.alpha.kubernetes.io/provider: public
    hosts:
      - host: &domain aliases.email.muehlbachler.io
        paths:
          - path: /
            pathType: ImplementationSpecific
            service:
              name: simplelogin
              port: 7777
    tls:
      - secretName: simplelogin-tls-cert
        hosts:
          - *domain

persistence:
  data:
    enabled: true
    type: emptyDir
    globalMounts:
      - path: /sl
  dkim-key:
    enabled: true
    type: secret
    name: dkim-key
    globalMounts:
      - path: /dkim.key
        subPath: private_key
  init:
    enabled: true
    type: configMap
    name: simplelogin-init
    defaultMode: 511
    advancedMounts:
      main:
        init:
          - path: /init.sh
            subPath: init.sh
