---
apiVersion: v2
name: authentik
description: Customized Authentik

version: 1.0.0

type: application

maintainers:
  - name: Daniel Muehlbachler-Pietrzykowski
    email: daniel@muehlbachler.io

appVersion: "0.0.0"

dependencies:
  - name: authentik
    version: 2023.5.5
    repository: https://charts.goauthentik.io
