---
global:
  projectEnvironment: production
  environment: prod
  spec:
    helm:
      valueFiles:
        - values.yaml
        - values-production.yaml
    enableAutomated: false # FIXME: enable again
