---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ak-outpost-ldap
spec:
  entryPoints:
    - ldaps
  routes:
    - match: HostSNI(`*`)
      services:
        - name: ak-outpost-ldap
          port: 389
          terminationDelay: 400
          nativeLB: true
          proxyProtocol:
            version: 2
  tls:
    secretName: authentik-tls-cert
    domains:
      - main: sso.dev.muehlbachler.io # FIXME:
