---
image:
  registry: registry.k8s.io
  repository: external-dns/external-dns
  tag: v0.15.0

crd:
  create: true

sources:
  - crd
  - service
  - ingress

interval: 2m

logLevel: warning

domainFilters:
  - muehlbachler.io
  - muehlbachler.xyz
annotationFilter: external-dns.alpha.kubernetes.io/provider=public
managedRecordTypesFilters:
  - A
  - AAAA
  - CNAME
  - MX
  - TXT

registry: noop
txtOwnerId: external-dns-public-services-cluster-prod
txtPrefix: extdns-
provider: google
google:
  serviceAccountSecret: external-dns-google
  project: muehlbachler-dns

resources:
  requests:
    cpu: 2m
    memory: 48Mi
  limits:
    cpu: 10m
    memory: 80Mi
