---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: doppler-access-secrets-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - ./secrets/secret-doppler-auth-aiven.enc.yml
  - ./secrets/secret-doppler-auth-authentik.enc.yml
  - ./secrets/secret-doppler-auth-cert-manager.enc.yml
  - ./secrets/secret-doppler-auth-email.enc.yml
  - ./secrets/secret-doppler-auth-external-dns.enc.yml
  - ./secrets/secret-doppler-auth-github.enc.yml
  - ./secrets/secret-doppler-auth-tailscale.enc.yml
