---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret-doppler-auth-authentik.enc.yml
  - ./secret-doppler-auth-database.enc.yml
  - ./secret-doppler-auth-email.enc.yml
